---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12

verifier:
  name: inspec

platforms:
  - name: amazonlinux-2018.03
    driver:
      box: hbsmith/awslinux
  - name: amazonlinux-2
    driver:
      box: bento/amazonlinux-2
  - name: osx-10.13
    driver:
      box: monsenso/macos-10.13
  - name: centos-6
    driver:
      box: centos/6
  - name: centos-7.2
    driver:
      box: bento/centos-7.2
  - name: ubuntu-bionic64
    driver:
      box: ubuntu/bionic64
  - name: ubuntu-xenial64
    driver:
      box: ubuntu/xenial64

suites:
  - name: default
    run_list:
      - recipe[osquery::default]
  - name: syslog
    attributes:
      osquery:
        syslog:
          pipe_user: 'root'
          pipe_group: 'root'
          pipe_filter : '*.info'
        options:
          verbose: true
          syslog_pipe_path: '/var/osquery/kitchen_pipe'
          enable_syslog: true
        schedule:
          time:
            query: 'SELECT * FROM time'
            interval: 10
          syslog:
            query: 'SELECT * FROM syslog'
            interval: 10
    run_list:
      - recipe[osquery::default]
  - name: osquery_wrapper_legacy
    run_list:
      - recipe[osquery_spec::osquery_wrapper]
    driver:
        require_chef_omnibus: 14.13
  - name: osquery_wrapper
    run_list:
      - recipe[osquery_spec::osquery_wrapper]
  - name: osquery_conf
    run_list:
      - recipe[osquery_spec::osquery_conf]
  - name: osquery_decorators
    run_list:
      - recipe[osquery_spec::osquery_decorators]