---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 13

verifier:
  name: inspec

platforms:
  - name: osx-1010
    driver:
      box: jhcook/osx-yosemite-10.10
      box_url: https://atlas.hashicorp.com/jhcook/boxes/osx-yosemite-10.10/versions/10.10.5/providers/virtualbox.box
  - name: centos-67
    driver:
      box: bento/centos-6.7
      box_url: https://atlas.hashicorp.com/bento/boxes/centos-6.7/versions/2.2.5/providers/virtualbox.box
  - name: centos-72
    driver:
      box: bento/centos-7.2
      box_url: https://atlas.hashicorp.com/bento/boxes/centos-7.2/versions/2.2.5/providers/virtualbox.box
  - name: ubuntu-trusty64
    driver:
      box: ubuntu/trusty64
      box_url: https://atlas.hashicorp.com/ubuntu/boxes/trusty64/versions/20160406.0.0/providers/virtualbox.box
  - name: ubuntu/precise64
    driver:
      box: ubuntu/precise64
      box_url: https://atlas.hashicorp.com/ubuntu/boxes/precise64/versions/20160329.0.0/providers/virtualbox.box
  - name: ubuntu/xenial64
    driver:
      box: ubuntu/xenial64
      box_url: https://atlas.hashicorp.com/ubuntu/boxes/xenial64/versions/20170418.0.0/providers/virtualbox.box

suites:
  - name: default
    run_list:
      - recipe[osquery::default]
  - name: syslog
    attributes:
      osquery:
        syslog:
          pipe_user: 'root'
          pipe_group: 'root'
          pipe_filter : '*.info'
        options:
          verbose: true
          syslog_pipe_path: '/var/osquery/kitchen_pipe'
          enable_syslog: true
        schedule:
          time:
            query: 'SELECT * FROM time'
            interval: 10
          syslog:
            query: 'SELECT * FROM syslog'
            interval: 10
    run_list:
      - recipe[osquery::default]
  - name: osquery_wrapper_legacy
    run_list:
      - recipe[osquery_spec::osquery_wrapper]
    driver:
        require_chef_omnibus: 11.18.12-1
  - name: osquery_wrapper
    run_list:
      - recipe[osquery_spec::osquery_wrapper]
  - name: osquery_conf
    run_list:
      - recipe[osquery_spec::osquery_conf]
  - name: osquery_decorators
    run_list:
      - recipe[osquery_spec::osquery_decorators]
